sudo: required
services:
  - docker

before_install:
  - docker build -t jigneshkvp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jigneshkvp/react-test npm run test -- --coverage

after_success:
  - docker build -t jigneshkvp/multi-client -f ./client/Dockerfile ./client
  - docker build -t jigneshkvp/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t jigneshkvp/multi-server -f ./server/Dockerfile ./server
  - docker build -t jigneshkvp/multi-worker -f ./worker/Dockerfile ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # The above images needs to be pushed to docker hub
  - docker push jigneshkvp/multi-client
  - docker push jigneshkvp/multi-nginx
  - docker push jigneshkvp/multi-server
  - docker push jigneshkvp/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-018553725402
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
